# Full Stack Pandas

In [1]:
import pandas as pd
import numpy as np
from IPython.display import HTML

Download the datasets from here:

https://www.kaggle.com/jessemostipak/hotel-booking-demand

https://www.kaggle.com/karangadiya/fifa19

## Basic EDA

In [2]:
df = pd.read_csv("hotel_bookings.csv")
fifa_df = pd.read_csv("data.csv", usecols=["Name", "Age", "Nationality", "Club", "Overall", "Value", "Wage"])

In [3]:
print("Dataset has {} rows and {} columns.".format(df.shape[0], df.shape[1]))

Dataset has 119390 rows and 32 columns.

In [4]:
df.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22

In [5]:
fifa_df.head(10)

,Name,Age,Nationality,Overall,Club,Value,Wage
0,L. Messi,31,Argentina,94,FC Barcelona,€110.5M,€565K
1,Cristiano Ronaldo,33,Portugal,94,Juventus,€77M,€405K
2,Neymar Jr,26,Brazil,92,Paris Saint-Germain,€118.5M,€290K
3,De Gea,27,Spain,91,Manchester United,€72M,€260K
4,K. De Bruyne,27,Belgium,91,Manchester City,€102M,€355K
5,E. Hazard,27,Belgium,91,Chelsea,€93M,€340K
6,L. Modrić,32,Croatia,91,Real Madrid,€67M,€420K
7,L. Suárez,31,Uruguay,91,FC Barcelona,€80M,€455K
8,Sergio Ramos,32,Spain,91,Real Madrid,€51M,€380K
9,J. Oblak,25,Slovenia,90,Atlético Madrid,€68M,€94K

## Memory Usage

In [6]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 106.7 MB

In [7]:
df.memory_usage()

Index                                128
hotel                             955120
is_canceled                       955120
lead_time                         955120
arrival_date_year                 955120
arrival_date_month                955120
arrival_date_week_number          955120
arrival_date_day_of_month         955120
stays_in_weekend_nights           955120
stays_in_week_nights              955120
adults                            955120
children                          955120
babies                            955120
meal                              955120
country                           955120
market_segment                    955120
distribution_channel              955120
is_repeated_guest                 955120
previous_cancellations            955120
previous_bookings_not_canceled    955120
reserved_room_type                955120
assigned_room_type                955120
booking_changes                   955120
deposit_type                      955120
agent                             955120
company                           955120
days_in_waiting_list              955120
customer_type                     955120
adr                               955120
required_car_parking_spaces       955120
total_of_special_requests         955120
reservation_status                955120
reservation_status_date           955120
dtype: int64

In [8]:
df.memory_usage(deep=True)

Index                                 128
hotel                             8079250
is_canceled                        955120
lead_time                          955120
arrival_date_year                  955120
arrival_date_month                7510011
arrival_date_week_number           955120
arrival_date_day_of_month          955120
stays_in_weekend_nights            955120
stays_in_week_nights               955120
adults                             955120
children                           955120
babies                             955120
meal                              7052193
country                           7148457
market_segment                    7882100
distribution_channel              7443167
is_repeated_guest                  955120
previous_cancellations             955120
previous_bookings_not_canceled     955120
reserved_room_type                7879740
assigned_room_type                7879740
booking_changes                    955120
deposit_type                      7999130
agent                              955120
company                            955120
days_in_waiting_list               955120
customer_type                     8024100
adr                                955120
required_car_parking_spaces        955120
total_of_special_requests          955120
reservation_status                7834309
reservation_status_date           7999130
dtype: int64

## Eval

In [9]:
# Commenting this section out as it consumes a lot of memory
#nrows, ncols = 1000000, 100
#df_A, df_B, df_C, df_D = (pd.DataFrame(np.random.randn(nrows, ncols)) for i in range(4))

In [10]:
#%timeit df_A + df_B + df_C + df_D

In [11]:
#%timeit pd.eval('df_A + df_B + df_C + df_D')

## Query

In [12]:
df.query('adults > 2 and lead_time < 40')

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
37,Resort Hotel,0,36,2015,July,27,2,1,3,3,...,No Deposit,241.0,NaN,0,Transient,108.80,0,1,Check-Out,2015-07-06
113,Resort Hotel,0,29,2015,July,27,4,2,6,3,...,No Deposit,241.0,NaN,0,Transient,116.50,0,1,Check-Out,2015-07-12
125,Resort Hotel,0,32,2015,July,27,4,0,1,4,...,No Deposit,NaN,NaN,0,Transient,0.00,0,1,Check-Out,2015-07-05
199,Resort Hotel,0,0,2015,July,28,7,0,1,3,...,No Deposit,NaN,NaN,0,Transient,195.00,1,0,Check-Out,2015-07-08
201,Resort Hotel,0,8,2015,July,28,7,0,4,3,...,No Deposit,240.0,NaN,0,Transient,193.00,0,1,Check-Out,2015-07-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119139,City Hotel,0,6,2017,August,35,27,2,1,3,...,No Deposit,9.0,NaN,0,Transient,196.33,0,2,Check-Out,2017-08-30
119233,City Hotel,0,28,2017,August,35,30,0,2,3,...,No Deposit,9.0,NaN,0,Transient,210.00,0,0,Check-Out,2017-09-01
119280,City Hotel,0,30,2017,August,35,30,0,3,3,...,No Deposit,7.0,NaN,0,Transient,195.47,0,3,Check-Out,2017-09-02
119289,City Hotel,0,25,2017,August,35,30,0,3,3,...,No Deposit,9.0,NaN,0,Transient,236.33,0,3,Check-Out,2017-09-02
119299,City Hotel,0,26,2017,August,35,29,0,4,3,...,No Deposit,9.0,NaN,0,Transient,207.25,0,0,Check-Out,2017-09-02

In [13]:
df[(df['adults'] > 2) & (df['lead_time'] < 40)]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
37,Resort Hotel,0,36,2015,July,27,2,1,3,3,...,No Deposit,241.0,NaN,0,Transient,108.80,0,1,Check-Out,2015-07-06
113,Resort Hotel,0,29,2015,July,27,4,2,6,3,...,No Deposit,241.0,NaN,0,Transient,116.50,0,1,Check-Out,2015-07-12
125,Resort Hotel,0,32,2015,July,27,4,0,1,4,...,No Deposit,NaN,NaN,0,Transient,0.00,0,1,Check-Out,2015-07-05
199,Resort Hotel,0,0,2015,July,28,7,0,1,3,...,No Deposit,NaN,NaN,0,Transient,195.00,1,0,Check-Out,2015-07-08
201,Resort Hotel,0,8,2015,July,28,7,0,4,3,...,No Deposit,240.0,NaN,0,Transient,193.00,0,1,Check-Out,2015-07-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119139,City Hotel,0,6,2017,August,35,27,2,1,3,...,No Deposit,9.0,NaN,0,Transient,196.33,0,2,Check-Out,2017-08-30
119233,City Hotel,0,28,2017,August,35,30,0,2,3,...,No Deposit,9.0,NaN,0,Transient,210.00,0,0,Check-Out,2017-09-01
119280,City Hotel,0,30,2017,August,35,30,0,3,3,...,No Deposit,7.0,NaN,0,Transient,195.47,0,3,Check-Out,2017-09-02
119289,City Hotel,0,25,2017,August,35,30,0,3,3,...,No Deposit,9.0,NaN,0,Transient,236.33,0,3,Check-Out,2017-09-02
119299,City Hotel,0,26,2017,August,35,29,0,4,3,...,No Deposit,9.0,NaN,0,Transient,207.25,0,0,Check-Out,2017-09-02

## Interpolation

In [14]:
subset_df = df['adr'].sample(10)

In [15]:
subset_df = subset_df.mask(np.random.random(subset_df.shape) < 0.3)

In [16]:
subset_df

94028        NaN
59558     126.67
106263     90.10
98980     152.00
96426        NaN
70929      80.00
24237        NaN
89987      65.00
65800      99.00
78449     155.00
Name: adr, dtype: float64

In [17]:
subset_df.interpolate()

94028        NaN
59558     126.67
106263     90.10
98980     152.00
96426     116.00
70929      80.00
24237      72.50
89987      65.00
65800      99.00
78449     155.00
Name: adr, dtype: float64

## Testing

In [18]:
df2 = df.copy()

In [19]:
df2.lead_time = df2.lead_time.astype('float')

In [20]:
#pd.testing.assert_frame_equal(df, df2)

In [21]:
df.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22

## Styling

In [22]:
fifa_df[['Value', 'Wage']] = fifa_df[['Value', 'Wage']].apply(lambda s: 
    s.replace('[\€,)]','', regex=True))

In [23]:
fifa_df['Value'] = fifa_df['Value'].replace({'K':'*1e3', 'M':'*1e6'}, regex=True).map(pd.eval).astype(float)
fifa_df['Wage'] = fifa_df['Wage'].replace({'K':'*1e3', 'M':'*1e6'}, regex=True).map(pd.eval).astype(float)

In [24]:
fifa_df.head(100).sample(100).style.format({"Value": "€{:20,.0f}", "Wage": "€{:20,.0f}"})\
                 .bar(subset='Value', color='lightblue')\
                 .bar(subset='Wage', color='orange')\
                 .background_gradient(subset='Overall', cmap='winter_r')\
                 .applymap(lambda x: f"color: {'red' if x >= 30 else 'black'}", subset='Age')